### PR TITLE
Corrections and implementation

### PR DESCRIPTION
**Pull request by TrackerSB**
Add basic files like gitattributes and gitignore, remove generated output files from repository and add a basic implementation that executs test cases, waits for them to finish and retrieves their result.

### CODE REVIEW

**Review by nganntt — APPROVED** [review]

**Review by nganntt — APPROVED** [review]

**Review by nganntt — APPROVED** [review]

**Review by nganntt — APPROVED** [review]

**Review by nganntt — COMMENTED** [review]
This file is a template which contents variables to generate the testcases. I found that the variables deleted.

**Review by nganntt — APPROVED** [review]

**Review by nganntt — APPROVED** [review]

**Comment by TrackerSB** [comment]
These files contain the generated output, don't they?

**Review by nganntt — APPROVED** [review]

**Review by nganntt — APPROVED** [review]

**Review by nganntt — APPROVED** [review]

**Review by nganntt — COMMENTED** [review]
Why do we need to add this. The script will generate theses testcase automatically

**Comment by TrackerSB** [comment]
Exactly. I removed them from the repo, didn't I? 

I missed the template file and test case file during the review. I am sorry for this inconvenience



On Wed, Aug 21, 2019 at 12:17 PM +0200, "Ngan Nguyen" <notifications@github.com> wrote:












@nganntt commented on this pull request.



Why do we need to add this. The script will generate theses testcase automatically

**Review by nganntt — APPROVED** [review]

**Review by nganntt — COMMENTED** [review]
Thank you very much for your correction.

**Pull request merged**
